openapi: 3.0.0
info:
  title: CrimePoirot API
  description: API documentation for the CrimePoirot project. This API enables repository analysis using Safety and integration with MongoDB.
  version: 1.0.0

servers:
  - url: http://localhost:5003
    description: Local development server for Safety analysis

paths:
  /analyze:
    post:
      summary: Analyze a repository using Safety and store the results in MongoDB.
      description: Clones a repository, runs Safety scan, and stores the vulnerabilities found in MongoDB.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                repo_url:
                  type: string
                  description: The URL of the Git repository to analyze.
                  example: "https://github.com/user/repo.git"
      responses:
        '200':
          description: Successfully analyzed the repository and stored the results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Analysis complete"
                  data:
                    type: object
                    properties:
                      repo_name:
                        type: string
                        example: "repo"
                      vulnerabilities:
                        type: array
                        items:
                          type: object
                          properties:
                            package_name:
                              type: string
                              example: "package_name"
                            version:
                              type: string
                              example: "1.0.0"
                            vulnerabilities_found:
                              type: integer
                              example: 2
        '400':
          description: Repository URL is required or invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  tool:
                    type: string
                    example: "safety"
                  message:
                    type: string
                    example: "Repository URL is required"
                  data:
                    type: object
                    nullable: true
        '404':
          description: Directory for repository does not exist.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  tool:
                    type: string
                    example: "safety"
                  message:
                    type: string
                    example: "The directory /tmp/repos/repo_name does not exist"
                  data:
                    type: object
                    nullable: true
        '500':
          description: Error running the safety scan or any other internal error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  tool:
                    type: string
                    example: "safety"
                  message:
                    type: string
                    example: "Error running safety scan: [error details]"
                  data:
                    type: object
                    nullable: true
          
  /Safety/{repo_name}/final_results:
    get:
      summary: Retrieve final Safety results for a repository.
      description: Fetches the Safety scan results and stores the final vulnerability count in MongoDB.
      parameters:
        - name: repo_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the repository to retrieve final results for.
          example: "repo"
      responses:
        '200':
          description: Successfully retrieved and processed the Safety results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Results stored successfully"
        '404':
          description: Report or results key not found in MongoDB.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "'results' key not found in the report."
        '500':
          description: Internal server error or failure to insert results into the `final_results` collection.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Failed to insert results into final_results"
        '502':
          description: Failed to retrieve Safety report for the repository from MongoDB.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Failed to retrieve Safety report for 'repo_name'"
